# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0005_exchrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='ru_stock',
        ),
        migrations.AddField(
            model_name='battery',
            name='ru_stock',
            field=models.NullBooleanField(verbose_name='RU stock', null=True, blank=True),
        ),

    ]
